---
version: 3
# format described here: https://ansible-builder.readthedocs.io/en/stable/definition/

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  system:
    - git [platform:rpm]
    - ipmitool [platform:rpm]

  python:
    - dnspython
    - pytz
    - ansible-lint
    - proxmoxer

  galaxy:
    collections:
      - name: awx.awx
      - name: community.general
      - name: ansible.posix
      - name: community.general
      - name: netbox.netbox
      - name: community.hashi_vault
      - name: freeipa.ansible_freeipa
      - name: ansible.utils
      - name: fedora.linux_system_roles

  python_interpreter:
    package_system: "python39"
    python_path: "/usr/bin/python3.9"

additional_build_steps:
  append_base:
    # we need this git in advance because galaxy needs that in early phase, 
    # actually before system requirements are processed.
    - RUN dnf -y install git unzip wget tree

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: –-no-deps
