---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream8

dependencies:
  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  system:
    - iputils [platform:rpm]
    - git [platform:rpm]

  python:
    - dnspython
    - pytz
    - ansible-lint

  galaxy:
    collections:
      - name: awx.awx
      - name: community.general
      - name: ansible.posix
      - name: community.general
      - name: netbox.netbox
    roles:
      - src: https://github.com/jose-d/ood-ansible.git
        version: master
      - src: https://github.com/willshersystems/ansible-sshd.git
        version: v0.19.0
      - src: https://github.com/galaxyproject/ansible-cvmfs.git
        version: 0.2.21
  python_interpreter:
    package_system: "python39"
    python_path: "/usr/bin/python3.9"

additional_build_steps:
  append_base:
    # we need this git in advance because galaxy needs that in early phase, 
    # actually before system requirements are processed.
    - RUN dnf -y install git
