---
version: 3
# format described here: https://ansible-builder.readthedocs.io/en/stable/definition/

images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  ansible_core:
    package_pip: ansible-core

  ansible_runner:
    package_pip: ansible-runner

  system:
    - git [platform:rpm]

  python:
    - dnspython
    - pytz
    - ansible-lint

  galaxy:
    collections:
      - name: awx.awx
      - name: community.general
      - name: ansible.posix
      - name: community.general
      - name: netbox.netbox
    roles:
      - src: https://github.com/jose-d/ood-ansible.git
        version: master
      - src: https://github.com/willshersystems/ansible-sshd.git
        version: v0.19.0
      - src: https://github.com/galaxyproject/ansible-cvmfs.git
        version: 0.2.21

  python_interpreter:
    package_system: "python39"
    python_path: "/usr/bin/python3.9"

additional_build_steps:
  append_base:
    # we need this git in advance because galaxy needs that in early phase, 
    # actually before system requirements are processed.
    - RUN dnf -y install git unzip wget tree
  prepend_final:
    - RUN wget https://github.com/bitwarden/clients/releases/download/cli-v2023.5.0/bw-linux-2023.5.0.zip -O bwcli.zip
    - RUN unzip bwcli.zip -d /usr/local/bin/ 
    - RUN tree /usr/local

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_ROLE_OPTS: –-no-deps
