[project]
name = "phoebe-aee"
version = "0.1.0"
description = "Environment to build Ansible executable environment"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ansible-builder>=3.1.0",
    "ansible-navigator>=3.4.1",
]
