---
collections:
  - name: awx.awx
  - name: community.general
  - name: ansible.posix
  - name: community.general
  - name: netbox.netbox 
roles:
  - src: https://github.com/jose-d/ood-ansible.git
    version: master
  - src: https://github.com/willshersystems/ansible-sshd.git
    version: v0.19.0
  - src: https://github.com/galaxyproject/ansible-cvmfs.git
    version: 0.2.21
