name: Build AEE
run-name: ${{ github.actor }} is attempting to buid ansible execution environment docker image
on: workflow_dispatch
permissions: write-all
env:
  SOMEVAR: something
jobs:
  prolog:
    name: Generate release tag from current datestring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .
  
      - name: Run some command
        id: run_some_command
        run: |
          sudo apt install podman
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Build image
        id: build_image
        run: |
          uv run ansible-builder build --verbosity 2 --tag phoebe_aee
          
