name: Build AEE
run-name: ${{ github.actor }} is attempting to buid ansible execution environment docker image
on: workflow_dispatch
permissions: write-all
env:
  SOMEVAR: something
jobs:
  prolog:
    name: Generate release tag from current datestring
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Cache Podman
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache/podman
          key: ${{ runner.os }}-podman-${{ hashFiles('**/Podmanfile') }}
          restore-keys: |
            ${{ runner.os }}-podman-
  
      - name: Ensure podman and uv is installed
        id: run_some_command
        run: |
          sudo apt install podman
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Build AEE image using ansible-builder
        id: build_image
        run: |
          uv run ansible-builder build --verbosity 2 --tag phoebe_aee

      - name: Push To ghcr
        id: push-to-quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: phoebe_aee
          tags: latest
          registry: ghcr.io/jose-d
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Print image url
        run: echo "Image pushed to ${{ steps.push-to-quay.outputs.registry-paths }}"
          
